spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.53.2.17:8848
    alicloud:
      access-key: LTAI4G9e5NZHQbY68nPE4zSu
      secret-key: JLV8r58nrLmmrOpS5cEBFNweNF55rm
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: wuxiaoqing
  application:
    name: gulimall-third-party

server:
  port: 30000